" This is a compromise that allows the user to copy text from the
"   terminal with the mouse and move the cursor in the command line.
" To copy to the clipboard from the document body, select the desired
"   text, press the right mouse button (RMB) to show context menu,
"   and then select 'Copy'. When using the command line, like after
"   typing ':%s/foot/bar/', use SHIFT+RMB > Copy to copy and click
"   the mouse button to position the cursor.
" Use `set mouse=nvi` to enable mouse controls and copy-paste when
"   shift is pressed.
"
set mouse=c

set viminfofile=$HOME/.local/state/vim/viminfo
